/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Genre
 * Id: 6958a7a8-9795-4bd1-92fa-fca88c44a656
 * Codename: genre
 */
export type Genre =
  | 'electronic'
  | 'classical'
  | 'rock__n__roll'
  | 'hip_hop'
  | 'jazz';
