/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Music
 * Environment: Production
 * Project Id: ac256208-f87d-0098-2cec-d95d0c386c73
 */
export const languages = {
  /**
   * Default project language
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Default project language',
  },
};
