/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Music
 * Environment: Production
 * Project Id: ac256208-f87d-0098-2cec-d95d0c386c73
 */
export const roles = {
  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: 'a81410a7-6a3d-47f1-835d-3b879f4c7f02',
    name: 'Project manager',
  },
};
