/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Music
 * Environment: Production
 * Project Id: ac256208-f87d-0098-2cec-d95d0c386c73
 */
export const taxonomies = {
  /**
   * Genre
   */
  genre: {
    codename: 'genre',
    id: '6958a7a8-9795-4bd1-92fa-fca88c44a656',
    externalId: undefined,
    name: 'Genre',
    terms: {
      electronic: {
        codename: 'electronic',
        id: '4a674d54-6368-4ac6-a768-b6eefd70641a',
        externalId: undefined,
        name: 'Electronic',
        terms: {},
      },
      classical: {
        codename: 'classical',
        id: 'b28f0fd9-d0c8-4b5a-a11e-ac4edc8a6bdd',
        externalId: undefined,
        name: 'Classical',
        terms: {},
      },
      rock__n__roll: {
        codename: 'rock__n__roll',
        id: 'a991dc03-8cab-4bf6-90b7-13bcc70a6cd7',
        externalId: undefined,
        name: 'Rock N Roll',
        terms: {},
      },
      hip_hop: {
        codename: 'hip_hop',
        id: '914ec895-a61c-4f32-a55b-52bd45b66fcf',
        externalId: undefined,
        name: 'Hip Hop',
        terms: {},
      },
      jazz: {
        codename: 'jazz',
        id: '421669dd-7156-43a4-a5b5-98477e586e90',
        externalId: undefined,
        name: 'Jazz',
        terms: {},
      },
    },
  },
};
