import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Band } from './band';
import { Song } from './song';
import { Media } from './media';
import { Genre } from '../taxonomies/genre';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Album
 * Id: 9f3a6f51-81b8-497b-a381-cd32f7f1ad1d
 * Codename: album
 */
export type Album = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: 4369cbef-4998-4bb4-a489-e17c064ccfad
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Band (modular_content)
   * Required: false
   * Id: a8fe47cb-62fd-4464-b980-0d7d780f7da9
   * Codename: band
   */
  band: Elements.LinkedItemsElement<Band>;

  /**
   * Songs (modular_content)
   * Required: false
   * Id: 50896b49-7825-435e-9d02-2295d0a03310
   * Codename: songs
   */
  songs: Elements.LinkedItemsElement<Song>;

  /**
   * Date (text)
   * Required: false
   * Id: de7c3a17-cd89-4ac5-8e06-0ff644b06a7b
   * Codename: date
   */
  date: Elements.TextElement;

  /**
   * Description (text)
   * Required: false
   * Id: fe3e1d5e-3442-4436-9db4-006261edf5e2
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * Cover Art (modular_content)
   * Required: false
   * Id: 7d3079bc-d30d-4896-b2fa-5cdc32072988
   * Codename: cover_art
   */
  coverArt: Elements.LinkedItemsElement<Media>;

  /**
   * Genre (taxonomy)
   * Required: false
   * Id: 8067b03a-fa41-4187-97e4-0b040c83ba8e
   * Codename: genre
   */
  genre: Elements.TaxonomyElement<Genre>;
}>;
