import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Performers } from './performers';
import { Album } from './album';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Band
 * Id: a936559b-9c47-401e-9fd4-cc7cb04025c1
 * Codename: band
 */
export type Band = IContentItem<{
  /**
   * Name (text)
   * Required: false
   * Id: c10ea837-085e-461f-a382-e3c40e19c5c3
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Bio (rich_text)
   * Required: false
   * Id: eb88233c-c3d0-4e44-b87c-d9a433b2f3b1
   * Codename: bio
   */
  bio: Elements.RichTextElement;

  /**
   * Performers (modular_content)
   * Required: false
   * Id: 1b3aa0db-df6b-4a85-8c7b-ce070a935f4b
   * Codename: performers
   */
  performers: Elements.LinkedItemsElement<Performers>;

  /**
   * Albums (modular_content)
   * Required: false
   * Id: 58fe1cc6-fbe2-4e80-ab08-ba45de190db6
   * Codename: albums
   */
  albums: Elements.LinkedItemsElement<Album>;
}>;
