import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Instrument
 * Id: d341b81e-78d1-4d66-8c16-c753c18e97fa
 * Codename: instrument
 */
export type Instrument = IContentItem<{
  /**
   * Name (text)
   * Required: false
   * Id: badc6f49-80cf-4d25-b7e1-9318afd7e737
   * Codename: name
   */
  name: Elements.TextElement;
}>;
