import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Media
 * Id: e5f238a3-5c12-4638-9813-d360482bab15
 * Codename: media
 */
export type Media = IContentItem<{
  /**
   * Asset (asset)
   * Required: true
   * Id: 9c2f46f4-65d7-42bd-86c2-2fe64edf3760
   * Codename: asset
   */
  asset: Elements.AssetsElement;
}>;
