import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Performers
 * Id: 227d1aeb-1a1e-4383-8e70-07b708594944
 * Codename: performers
 */
export type Performers = IContentItem<{
  /**
   * Name (text)
   * Required: true
   * Id: 477d5385-7ec5-4fbe-b5fc-b35aa4f05a27
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Instruments (modular_content)
   * Required: false
   * Id: 1f5af6b8-a3b6-42a7-b7cd-a0b2ea8ce8e0
   * Codename: instruments
   */
  instruments: Elements.LinkedItemsElement<IContentItem>;
}>;
