import { IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Publisher
 * Id: e5cdb7a1-da72-4163-9e11-e874ab6c1912
 * Codename: publisher
 */
export type Publisher = IContentItem<{}>;
