import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Song
 * Id: 33cc5002-de47-4883-9bab-c13b9bd4e2f0
 * Codename: song
 */
export type Song = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 2b699bf9-e9f9-488c-9129-dc5e8c9405dd
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Length (text)
   * Required: false
   * Id: 1067da96-ab58-4aec-920c-606d66712c5d
   * Codename: length
   */
  length: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: c8758cac-2c35-40dc-8416-20064f1c2cbd
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Lyrics (rich_text)
   * Required: false
   * Id: a2094727-3dd1-4bb4-b38c-88067ba9db3c
   * Codename: lyrics
   */
  lyrics: Elements.RichTextElement;
}>;
